sudo: false
language: go
go:
  - 1.6.3

install:
  - ./install_protobuf.sh
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/golang/protobuf/protoc-gen-go

script:
  - ./generate.sh
